# Generated by Django 5.0.7 on 2024-08-19 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zonesprotgesdusngal',
            options={},
        ),
    ]
