# Generated by Django 5.0.7 on 2024-11-22 18:31

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_zonesprotgesdusngal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zonesprotgesdusngal',
            options={'ordering': ['nom']},
        ),
        migrations.AlterField(
            model_name='zonesprotgesdusngal',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=32628),
        ),
        migrations.AlterField(
            model_name='zonesprotgesdusngal',
            name='superf_ha_field',
            field=models.DecimalField(blank=True, db_column='superf_ha_', decimal_places=3, max_digits=13, null=True),
        ),
        migrations.CreateModel(
            name='NDVI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date ')),
                ('ndvi', models.FloatField(verbose_name='ndvi')),
                ('id_k', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.zonesprotgesdusngal', verbose_name='clef secondaire')),
            ],
        ),
    ]
